accounts2/urls.py
from django.urls import path, re_path, include
from . import views
from django.contrib.auth import views as auth_views , logout as auth_logout
from . import forms
from django.contrib.auth.views import LoginView


app_name = 'accounts2'

urlpatterns = [
    path('like_or_unlike', views.like_or_unlike, name="like_or_unlike"),
    path('logout', views.Logout, name="logout"),
    # path('login/', views.LoginView.as_view(template_name="login.html" , authentication_form= "forms.LoginForm"), name = 'login'),
    path('delete_for_my_favorite_user', views.delete_for_my_favorite_user, name="delete_for_my_favorite_user"),
    path('delete_for_liker_user_for_me', views.delete_for_liker_user_for_me, name="delete_for_liker_user_for_me"),

    path('signup/', views.signup, name='signup'),
    path('member_list/', views.member_list, name='member_list'),
    path('my_profile_information_view/', views.my_profile_information_view.as_view(), name = 'my_profile_information_view'),
    path('update_for_profile/<int:id>', views.update_for_profile , name='update_for_profile'),

    # 참고 wm MyShortcutListByUser
    path('user_profile_information_view/<str:user>', views.user_profile_information_view, name="user_profile_information_view"),
    path('delete_login_user/', views.delete_login_user, name="delete_login_user"),



]

challenge/urls.py
from django.urls import path, re_path , include
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings

app_name = 'challenge'

urlpatterns = [

    path('', views.ChallengeSubjectList.as_view() , name="challenge_subject_list"),
    path('delete_challenge_subject_by_id/<int:id>', views.delete_challenge_subject_by_id , name="delete_challenge_subject_by_id"),

    # 챌린지 대주제 입력 Create_Challenge_View
    path('Create_Challenge_View', views.CreateChallengeSubjectView.as_view() , name="CreateChallengeSubjectView"),
    path('update_challenge_subject/<int:pk>/', views.update_challenge_subject.as_view() , name='update_challenge_subject'),

    path('lecinfo/<int:pk>/delete', views.LecInfoDeleteView.as_view(), name='LecInfoDeleteView'),

    path ('<int:classification>', views.ParticipantsListForLectureView.as_view (), name="lec_record_list"),

    path('challenge_list/', views.challenge_list , name="challenge_list"),

    # path('<int:classification>', views.ParticipantsListForLectureView.as_view() , name="lec_record_list"),

	path('lecinfo_list/<str:challenge_title>', views.lecinfo_list_for_challenge, name="lecinfo_list_for_challenge"),
    # path('lecinfo_list', views.LecInfoListView.as_view() , name="lecinfo_list"),

    path('record/new/<int:classification>',views.CreateRecordView_11.as_view(), name ="네임"),
    path('lecinfo/new/<str:challenge_title>', views.CreatelecInfo.as_view() , name="CreatelecInfo"),
    # path('lec_info/new/',views.CreatelecInfo.as_view(), name ="create_lec_info"),

    path('record/delete/<int:pk>/<int:classification>', views.RecordDeleteView.as_view(), name='student_record_delete'),
    path('record/modify/<int:pk>/<int:classification>', views.RecordUpdateView.as_view(), name='student_record_update'),

    path('lec_info_update/<int:pk>/<int:classification>', views.LecInfoUpdateView.as_view(), name='lec_info_update'),

    path('<int:id>/recommand_lecture/', views.recommand_lecture, name="recommand_lecture"),
    path('like_or_unlike_for_challenge_subject', views.like_or_unlike_for_challenge_subject, name="like_or_unlike_for_challenge_subject"),



]

pd/urls.py
from django.urls import path, re_path , include
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings

app_name = 'pd'

urlpatterns = [
    path('private_task_list/', views.private_task_list.as_view() , name="private_task_list"),
    path('my_task/new/',views.mytask_new , name ="mytask_new"),
    path('delete_mytask_by_ajax/',views.delete_mytask_by_ajax , name ="delete_mytask_by_ajax"),
    path('update_mytask_by_ajax/',views.update_mytask_by_ajax , name ="update_mytask_by_ajax"),
    #
    # path('add_mysite_by_ajax/',views.add_mysite_by_ajax , name ="add_mysite_by_ajax"),
    # path('update_mysite_by_ajax/',views.update_mysite_by_ajax , name ="update_mysite_by_ajax"),
    # path('delete_mysite_by_ajax/',views.delete_mysite_by_ajax , name ="delete_mysite_by_ajax"),

]

reservation_app/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('accounts/', include('accounts2.urls')),
    path('accounts/', include('allauth.urls')),
    # path('logout/', auth_views.LogoutView, name = 'logout', kwargs = {'next_page' : settings.LOGIN_URL}),
    # re_path(r'^logout/$', auth_views.LogoutView, name = 'logout', kwargs = {'next_page' : settings.LOGIN_URL}),
    path('admin/', admin.site.urls),
    path('markdownx/', include('markdownx.urls')),
    path('blog/', include('blog.urls')),
    path('', include('remote_control.urls')),
    path('todo/', include('todo.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('bestlec/', include('bestlec.urls')),
    path('management/', include('management.urls')),
    path('challenge/', include('challenge.urls')),
    path('board/', include('board.urls')),
    path('pd/', include('pd.urls')),
    path('skilblog/', include('skilblog.urls')),
    path('wm/', include('wm.urls')),
    path('skilnote2/', include('skilnote2.urls')),
    path('skilnote3/', include('skilnote3.urls')),
    path('skilnote4/', include('skilnote4.urls')),
]

if settings.DEBUG:
   urlpatterns += static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   import debug_toolbar
   urlpatterns += [
      path ('__debug__/', include (debug_toolbar.urls)),
   ]

challenge/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget
from .models import LecInfo, challenge_subject

# from bootstrap_datepicker_plus import DatePickerInput

class LecInfoForm(forms.ModelForm):
    class Meta:
        model = LecInfo
        fields = ['lec_name', 'lec_url', 'git_url']

class challenge_subject_form(forms.ModelForm):
    class Meta:
        model = challenge_subject
        fields = ['title','description','home','image']

        widgets = {
            'title': forms.TextInput(attrs={'size': 120}),
            'home': forms.TextInput(attrs={'size': 120}),
            'description': SummernoteWidget(attrs={'summernote': {'width': '100%', 'height': '480px', 'line-height': 1.2, 'font-size':12, 'tabSize': 4, "backcolor":"white", 'color':"white", 'backColor' :'white'  }}),
        }

challenge/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.db.models import Q
from django.db.models import F
from django.urls import reverse_lazy
from django.contrib import messages
from django.urls import reverse
from .models import StudentRecord, LecInfo, RecommandLecInfo, challenge_subject, LikeChallengeSubject
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import LecInfoForm, challenge_subject_form
from django.contrib.auth.models import User
from django.http import HttpResponse, JsonResponse
from django.utils import timezone


# 1122
def delete_challenge_subject_by_id(request,id):
	user = request.user
	if request.method == "POST" and request.is_ajax():
		challenge = challenge_subject.objects.filter(Q(id=id)).delete()
		print("challenge_subject 삭제 성공 !!!!!!!!!!!!!!!!!!!", challenge)
		return JsonResponse({
			'message': 'challenge_subject 삭제 성공',
			})
	else:
		return redirect('/challenge')




class update_challenge_subject(UpdateView):
    model = challenge_subject
    form_class = challenge_subject_form

    def get_template_names(self):
        return ['challenge/challenge_subject_form.html']


# 챌린지 대주제(과목) 입력 뷰
class CreateChallengeSubjectView(LoginRequiredMixin,CreateView):
    model = challenge_subject
    form_class = challenge_subject_form

    def get_template_names(self):
        return ['challenge/challenge_subject_form.html']

    def form_valid(self, form):
        print("create challenge_subject(챌린지 과목) excute !!!!!!!!!!!!!!!!!!!!!!!!!!!!")
        ms = form.save(commit=False)
        ms.leader = self.request.user
        ms.created = timezone.now()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('challenge:challenge_subject_list')


def like_or_unlike_for_challenge_subject(request):
    target_id = request.POST.get('target_id', False)
    my_id = request.POST.get('liker', False)

    print("target_id ", target_id)
    print("my_id ", my_id)

    target_challenge =  get_object_or_404(challenge_subject, id=target_id)
    me =  get_object_or_404(User, username=my_id)
    print("추천 받는 챌린지 : " , target_challenge)
    print("추천 하는 사람 : ", me)

    recommand_count = LikeChallengeSubject.objects.filter(Q(challenge=target_challenge) & Q(author=me)).count() # 내가 추천한거 있는지 확인
    print("recommand_count : ", recommand_count)

    if (recommand_count ==  0):
        rc = LikeChallengeSubject.objects.create(challenge=target_challenge , author=me) # 나의 추천 추가
        print('추천 ++++++++++++++++++++++++++++++++++++++++++++++++++++++')
        recommand_count = LikeChallengeSubject.objects.filter(Q(challenge=target_challenge)).count() # 추천 받은 사람 점수 확인
        challenge = challenge_subject.objects.filter(Q(leader=target_challenge.leader)).update(like_count = recommand_count) # 추천 대상자 프로필 점수 반영

        return JsonResponse({
            'message': "추천 +1",
            "option":"plus",
            "recommand_count":recommand_count
        })

    else:
        LikeChallengeSubject.objects.filter(Q(challenge=target_challenge) & Q(author_id=me)).delete() # 내가 추천한거 삭제

        recommand_count = LikeChallengeSubject.objects.filter(Q(challenge=target_challenge)).count() # 추천 받은 사람 점수 확인
        print('추천 ---------------------------------------------------')
        challenge = challenge_subject.objects.filter(Q(leader=target_challenge.leader)).update(like_count = recommand_count)

        return JsonResponse({
            'message': "추천 -1 ",
            "option":"minus",
            "recommand_count":recommand_count
        })


class LecInfoDeleteView(DeleteView):
	model = LecInfo
	success_message = "challenge is removed"

	def get_success_url(self):
		challenge_title = self.object.challenge.title
		print("challenge_title : ", challenge_title)
		return reverse('challenge:lecinfo_list_for_challenge', kwargs={'challenge_title':challenge_title})

	def delete(self, request, *args, **kwargs):
		messages.success(self.request, self.success_message)
		return super(LecInfoDeleteView, self).delete(request, *args, **kwargs)

# 주제별 밑의 강의별 리스트

def lecinfo_list_for_challenge(request, challenge_title):
	print ("challenge subject 과목 관련 강의 리스트를 출력 합니다.")
	challenge = challenge_subject.objects.get (title=challenge_title)
	# lecinfo_list = LecInfo.objects.filter (challenge=challenge)
	lecinfo_list = challenge.lecinfo_set.all()
	print ('lecinfo_list : ', lecinfo_list)

	return render (request, 'challenge/lecinfo_list.html', {
		"lecinfo_list": lecinfo_list,
		"challenge_title": challenge_title,
        "challenge_leader": challenge.leader,
		"challenge_id":challenge.id,
		"challenge_image":challenge.image,
        "challenge_description":challenge.description
	})


# 주제별 리스트
class ChallengeSubjectList (LoginRequiredMixin, ListView):
	model = challenge_subject
	paginate_by = 10
	template_name = 'challenge/challenge_list.html'

	def get_queryset(self):
		return challenge_subject.objects.all().order_by('-like_count')


def challenge_list(request):
	return render (request, 'challenge/challenge_list.html', {
	})


def recommand_lecture(request, id):
	lecture = get_object_or_404 (LecInfo, pk=id)
	recommand_count = RecommandLecInfo.objects.filter (
		Q (author=request.user) & Q (lecinfo=lecture)).count ()
	print ("내가 강의 추천한 개수 : ", recommand_count)
	print ('id : ', id)

	id = str (id)

	if recommand_count < 1:
		lecinfo = RecommandLecInfo.objects.create (
			author=request.user, lecinfo=lecture)
		print ('추천을 추가')
	else:
		RecommandLecInfo.objects.filter (
			Q (author=request.user) & Q (lecinfo=lecture)).delete ()
		print ('추천을 삭제')

	return redirect ("/challenge/" + id)


# return reverse('challenge:lec_record_list', kwargs={'classification': id})


class CreatelecInfo (CreateView):
	model = LecInfo
	form_class = LecInfoForm
	success_message = "강의 정보 기록을 입력하였습니다."
	challenge_title = ""

	def get_template_names(self):
		return ['challenge/lecinfo_form.html']

	def form_valid(self, form):
		print ("CreateLecInfo 실행")
		fn = form.save (commit=False)
		fn.challenge = challenge_subject.objects.get(title=self.kwargs["challenge_title"])
		self.challenge_title = fn.challenge.title
		fn.manager = self.request.user
		return super ().form_valid (form)

	def get_context_data(self, **kwargs):
		ctx = super(CreatelecInfo, self).get_context_data(**kwargs)
		ctx['challenge_subject'] = self.kwargs["challenge_title"]
		return ctx

	def get_success_url(self):
		print("self.challenge_title : ", self.challenge_title)
		return reverse ('challenge:lecinfo_list_for_challenge', kwargs={'challenge_title':self.challenge_title})


class RecordUpdateView (UpdateView):
	model = StudentRecord
	fields = ['current_class']
	success_url = reverse_lazy ('challenge:lec_record_list')
	success_message = "record is modified"

	def get_success_url(self):
		classnum = self.kwargs['classification']
		return reverse ('challenge:lec_record_list', kwargs={'classification': classnum})


class LecInfoUpdateView (UpdateView):
	model = LecInfo
	fields = ['lec_name', 'manager', 'lec_url', 'git_url']

	def get_success_url(self):
		classnum = self.kwargs['classification']
		return reverse ('challenge:lec_record_list', kwargs={'classification': classnum})


class RecordDeleteView (DeleteView):
	model = StudentRecord
	success_message = "record is removed"

	def delete(self, request, *args, **kwargs):
		messages.success (self.request, self.success_message)
		return super (RecordDeleteView, self).delete (request, *args, **kwargs)

	def get_success_url(self):
		classnum = self.kwargs['classification']
		return reverse ('challenge:lec_record_list', kwargs={'classification': classnum})


# 강의 정보 및 참여자 정보
class ParticipantsListForLectureView (LoginRequiredMixin, ListView):
	model = StudentRecord
	paginate_by = 20
	ordering = ['-created']

	def get_queryset(self):
		print ("PostSearch 확인")
		classnum = self.kwargs['classification']
		object_list = StudentRecord.objects.filter (classification=classnum).order_by ('-created')
		print ("result : ", object_list)
		return object_list

	def get_context_data(self, *, object_list=None, **kwargs):
		classnum = self.kwargs['classification']
		lec_info = LecInfo.objects.get (id=classnum)
		context = super (ParticipantsListForLectureView, self).get_context_data (**kwargs)
		context['LecInfo'] = lec_info
		context['recommnad_count'] = RecommandLecInfo.objects.filter (
			lecinfo=lec_info).count ()

		return context


class LecInfoListView (LoginRequiredMixin, ListView):
	model = LecInfo
	paginate_by = 20


	def get_context_data(self, *, object_list=None, **kwargs):
		classnum = self.kwargs['challenge_title']
		return context


class CreateRecordView_11 (CreateView):
	model = StudentRecord
	fields = ['current_class', 'github_url']
	success_message = "강의 수강 기록을 입력하였습니다."

	def form_valid(self, form):
		classnum = self.kwargs['classification']

		print ("CreateRecordView 실행")
		fn = form.save (commit=False)
		fn.author = self.request.user

		lec = LecInfo.objects.get (id=classnum)
		fn.classification = lec

		return super ().form_valid (form)

	def get_success_url(self):
		classnum = self.kwargs['classification']
		return reverse ('challenge:lec_record_list', kwargs={'classification': classnum})

challenge/templates/challenge/challenge_list.html
{% extends "challenge/layout.html" %}
{% load static %}
{% load bootstrap4 %}


{%block title %} Challenge Subject {% endblock %}

{%block extra_css %}
<link rel="{% static 'challange/challange.css' %}" type="text/css" href="theme.css">
{% endblock %}

{%block content5 %}
<br><br><br><br>

<button class="new3_btn btn btn-outline-dark btn-block mt-2" onclick="window.location.href = '{% url 'challenge:CreateChallengeSubjectView' %}';">create</button> <br>

{% if object_list.exists %}


<div class="row mt-2">

	{% for p in object_list %}
	<div class="card mt-2 ml-2" style="width: 20rem;">
		<!--		<img class="card-img-top" src="..." alt="Card image cap">-->
		<div class="card-body">

				<div class="container">
					<div class="row">
						<div class="">
							<span class="card-title ">{{ forloop.counter }}</span>
						</div>

						<div class="col p-1">
							<!-- <img src="{% static 'icon/askdjango_icon.jpg' %}" width="100%" alt=""> -->
							{% if p.image %}
								<img class="card-img-top" src={{ p.image.url }} alt="Card image cap" width="100%" height="80px">
							{% endif %}

						</div>

						<div class="col p-1">
							<div class="mb-2">{{p.title}}</div>
							<div class="">
								명성 : {{p.like_count}} 점 <br>
								모임 : {{p.lecinfo_count2}} 개
							</div>
						</div>
						<div class="col p-1">
							<a href="{% url 'challenge:lecinfo_list_for_challenge' p.title %}"
							   class="btn btn-outline-dark btn-block float-right">
							   go
						   </a>
						   <!-- <button type="button" name="button" class="mt-2">plus</button> -->
						   <button type="button" class="plus_minus_for_challenge btn btn-outline-warning mt-2" data-target_id="{{p.id}}" data-my_id="{{request.user.id}}">
							   <img src="{% static 'icon/plus.png' %}" alt="">
						   </button>
						</div>
					</div>
					<div class="row mt-4">
						{% ifequal p.leader request.user %}
						<div class="container">
							<div class="row">
								<div class="col">
									<a href="{% url "challenge:update_challenge_subject" p.id %}" class="btn btn-outline-danger float-right btn-block">update</a>
								</div>
								<div class="col">
									<button class="btn btn-outline-primary delete_challenge_subject_button float-right btn-block" data-url="{% url 'challenge:delete_challenge_subject_by_id' p.id %}"{{p.id}}">삭제</button>

								</div>
							</div>
						</div>
						{% else %}
						{% endifequal %}
					</div>
				</div>

			</h5>
		</div>
	</div>
	{% endfor %}
</div>

{% else %}
<tr>
	<td colspan="">
		<h4>no subject!</h4>
	</td>
</tr>
{% endif %}

<div class="mt-4">
	{% if is_paginated %}
	{% bootstrap_pagination page_obj size="small" justify_content="center" %}
	{% endif %}

	{% endblock %}
</div>

<script type="text/javascript">

// js area

{% block extra_js %}

$('body').on('click', '.delete_challenge_subject_button', function (e) {
	e.preventDefault();
	const delete_url = $(this).data("url");

	$.ajax({
		type: "POST",
		url: delete_url,
		data: {
			csrfmiddlewaretoken: '{{ csrf_token }}'
		},
		success: function (result) {
			{% comment %} $("#shortcut_" + id).remove(); {% endcomment %}
			alert(result.message);
			window.location.href = "/challenge/"
		}
	});

});


$('body').on('click', '.plus_minus_for_challenge', function (e) {

	// 좋아요 받을 대상의 id
    const target_id =  $(this).data("target_id");
	// 좋아요 누르는 사람
    const liker = "{{request.user}}"

    $.ajax({
        type: "POST",
        url: '/challenge/like_or_unlike_for_challenge_subject',
        data: {
            target_id : target_id,
            liker: liker,
            csrfmiddlewaretoken: '{{ csrf_token }}',
        },
        success: function (result) {
			alert(result.message)
			window.location.href = "/challenge/"
        },
        error:{
            function(err){
                console.log("err : ", err.statusText);
            }
        }
    });

});

{% endblock %}

</script>

challenge/templates/challenge/layout.html
{% extends "layout.html" %}

challenge/templates/challenge/lecinfo_list.html
{% extends "layout.html" %}

{%block title %}{{challenge_title}} 에 대한 Challenge List{% endblock %}

{%block content2 %}

<br><br>

<div class="jumbotron">
	<div class="container">
		<div class="row p-0">
			<div class="col p-0">
				<h4 class="display-4">{{challenge_title}}</h4>
				challenge 개설자 : {{challenge_leader}} <br>
				{{challenge_description | safe }}
			</div>
			<div class="col">

			</div>
			<div class="col">
			</div>
			<div class="col p-0">
				{% if challenge_image %}
				<img class="" src="{{ challenge_image.url }}" alt="Card image cap" width="80%" height="80%">
				{% endif %}
			</div>
		</div>
		<div class="row mt-2">
		</div>
	</div>
</div>

<button class="new3_btn btn btn-outline-dark float-right ml-1" onclick="window.location.href = '{% url 'challenge:challenge_subject_list' %}';">목록으로 이동</button>
<button class="new3_btn btn btn-outline-dark float-right ml-1" onclick="window.location.href = '{% url 'challenge:CreatelecInfo' challenge_title %}';">소모임 추가</button>


<br><br><br><br>

{% if lecinfo_list.exists %}
{% for p in lecinfo_list %}
<div class="row">
	<div class="col-sm-12">
		<div class="card">
			<div class="card-body">
				<p class="card-text">
					<h4>{{p.lec_name}}</h4><br>

					<span>
						<a href="{% url 'accounts2:user_profile_information_view' p.manager %}">{{p.manager}}</a>
						팀장 &nbsp;&nbsp;
						{{p.student_count2}} 명 참여 &nbsp;&nbsp;
					</span>
					<!-- <h6>{{p.student_count2}} 명 참여</h6> -->
					<!-- <h6>{{p.lec_reputation}} 평점</h6> -->
					<a href="{% url 'challenge:lec_record_list' p.id %}" class="btn btn-primary float-right">입장</a>
				</p>
			</div>
		</div>
	</div>
</div>
<br><br>
{% endfor %}
{% else %}
<tr>
	<td colspan="6">
		<h4>아직 챌린지 모임이 없습니다.</h4>
	</td>
</tr>
{% endif %}


{% endblock %}
<script type="text/javascript">
{% block extra_js %}

{% endblock %}

</script>

challenge/templates/challenge/studentrecord_list.html
{% extends "layout.html" %}

{%block title %}소모임 참여자 정보{% endblock %}
{% load static %}

{%block content4 %}

{%block extra_head %}

{% endblock %}


<br><br><br><br>

<div class="jumbotron">
	<div class="container">
		<div class="row p-0">
			<div class="col p-0">
				<h4 class="display-6">{{LecInfo.lec_name}}</h4>
			</div>
			<div class="col p-0">
                <div class="float-right">
                    평점:
                    <input type="text" name="" value="{{recommnad_count}}">
                    <a href="{% url "challenge:recommand_lecture" LecInfo.pk %}">
                        <img src="{% static 'icon/plus.png' %}" alt="">
                    </a>
                </div>
			</div>
		</div>
		<div class="row mt-2">
            <div class="col p-0">
                과목 담당자:  <a href="{% url 'accounts2:user_profile_information_view' LecInfo.manager %}">{{LecInfo.manager}}</a>
				<br>
                강의 url :
				<a href="{{LecInfo.lec_url }}">
					{{LecInfo.lec_url }}
				</a>
            </div>
            <div class="col p-0">
                {%if request.user.username == LecInfo.manager  %}
                    <a class="btn btn-outline-dark float-right" href="{% url "challenge:lecinfo_list_for_challenge" LecInfo.challenge.title %}">목록</a>
                    <a class="btn btn-outline-dark float-right" href="{% url "challenge:LecInfoDeleteView" LecInfo.id %}">삭제</a>
                    <a href="{% url "challenge:lec_info_update" LecInfo.id LecInfo.id %}" class="btn btn-outline-dark float-right">수정</a>
                {% else %}
                {% endif %}
            </div>
		</div>
	</div>
</div>

{% if messages %}
<div class="alert alert-success">
    {% for message in messages %}
     {{ message.message }}<strong>{{ message.tags }}</strong>
     {% endfor %}
</div>
{% endif %}

<a href="/challenge/record/new/{{LecInfo.id}}" class="btn btn-outline-warning float-right">입력(input)</a>
<br><br>
<table class="table table-bordered" id="todo_list">
    <tr>
        <td>check</td>
        <td>index</td>
        <td>author</td>
        <td>current_class</td>
        <td>github</td>
    </tr>

    {% if object_list.exists %}
        {% for p in object_list %}
            <tr>
                <td>
                    <input type="checkbox" id="{{p.pk}}" class="td_check">
                </td>
                <td>
                    {{ forloop.counter }}
                </td>
                <td>
					<a href="{% url 'accounts2:user_profile_information_view' p.author %}">{{p.author}}</a>

                    <a href="{% url 'wm:skil_note_list_by_user' p.author 1 %}" class="badge badge-dark " >skilnote</a>

                </td>
                <td>
                    {{p.current_class}}

                    {% if request.user == p.author %}
                        <a class="badge badge-pill badge-primary btn-sm" href="{% url "challenge:student_record_delete" p.id LecInfo.id %}">삭제</a>
                        <a class="badge badge-pill badge-primary btn-sm" href="{% url "challenge:student_record_update" p.id LecInfo.id %}">수정</a>
                    {% endif %}

                </td>
                <td>

                    <a class="go_to_next_channer_btn btn btn-outline-primary" href={{p.github_url}}>
                        <img src="{% static 'icon/github.png' %}" alt="">
                    </a>

                </td>
            </tr>
        {% endfor %}
    {% else %}
        <tr>
            <td colspan="7">
                <h4>아직 게시물이 없습니다.</h4>
            </td>
        </tr>
    {% endif %}
</table>

<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Modal Header2</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <p>Some text in the modal.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

{% endblock %}
<script type="text/javascript">
{% block extra_js %}

$(document).ready(function(){
    $('.movetoshortcut').click(function(e){
        e.preventDefault();

        const id = this.id
        const user_id = $(this).data("user_id")

        // alert("id : " + id)
        // alert("user_id : " +user_id)

        window.history.pushState("", "", '/wm/')

        $.ajax({
          type: "POST",
          url: 'update/shortcut_id_ajax/'+id,
          data: {
              'user_id':user_id,
              csrfmiddlewaretoken: '{{ csrf_token }}'
          },
            success: function(result) {
                // alert('update for user shortcut id is success ');
                console.log("result : ", result);
                // alert("result.message :     shorcut page로 이동")
                var url = "http://terecal-hyun.co.kr/wm/myshortcut/"+user_id+"/1"
                document.location.href = url
            }
        });
    })


    $("#insert_record_btn").click(function(){
        $("#myModal").modal();
    });

});

{% endblock %}
</script>