bestlec/urls.py
from django.urls import path, re_path , include
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings

app_name = 'bestlec'

urlpatterns = [
    path('', views.Best20List.as_view() , name="best20_list"),
    path('<int:id>/grade_plus/', views.grade_plus, name="request_grade_plus"),
    path('new/',views.bestlec_new , name ="bestlec_new"),
    path('<int:id>/finisherlist', views.FinisherList , name="FinisherList"),
    path('<int:bl_pk>/finisher/new', views.FinisherCreateView.as_view(), name="finisher_new"),
    path('<int:id>/recommand_lecture/', views.recommand_lecture, name="recommand_lecture"),

    path('<int:pk>/delete/', views.best20_delete, name='best20_delete'),
    path('<int:pk>/finisher/delete/', views.finisher_delete, name='finisher_delete'),

]

pd/urls.py
from django.urls import path, re_path , include
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings

app_name = 'pd'

urlpatterns = [
    path('private_task_list/', views.private_task_list.as_view() , name="private_task_list"),
    path('my_task/new/',views.mytask_new , name ="mytask_new"),
    path('delete_mytask_by_ajax/',views.delete_mytask_by_ajax , name ="delete_mytask_by_ajax"),
    path('update_mytask_by_ajax/',views.update_mytask_by_ajax , name ="update_mytask_by_ajax"),
    #
    # path('add_mysite_by_ajax/',views.add_mysite_by_ajax , name ="add_mysite_by_ajax"),
    # path('update_mysite_by_ajax/',views.update_mysite_by_ajax , name ="update_mysite_by_ajax"),
    # path('delete_mysite_by_ajax/',views.delete_mysite_by_ajax , name ="delete_mysite_by_ajax"),

]

reservation_app/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('accounts/', include('accounts2.urls')),
    path('accounts/', include('allauth.urls')),
    # path('logout/', auth_views.LogoutView, name = 'logout', kwargs = {'next_page' : settings.LOGIN_URL}),
    # re_path(r'^logout/$', auth_views.LogoutView, name = 'logout', kwargs = {'next_page' : settings.LOGIN_URL}),
    path('admin/', admin.site.urls),
    path('markdownx/', include('markdownx.urls')),
    path('blog/', include('blog.urls')),
    path('', include('remote_control.urls')),
    path('todo/', include('todo.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('bestlec/', include('bestlec.urls')),
    path('management/', include('management.urls')),
    path('challenge/', include('challenge.urls')),
    path('board/', include('board.urls')),
    path('pd/', include('pd.urls')),
    path('skilblog/', include('skilblog.urls')),
    path('wm/', include('wm.urls')),
    path('skilnote2/', include('skilnote2.urls')),
    path('skilnote3/', include('skilnote3.urls')),
    path('skilnote4/', include('skilnote4.urls')),
]

if settings.DEBUG:
   urlpatterns += static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   import debug_toolbar
   urlpatterns += [
      path ('__debug__/', include (debug_toolbar.urls)),
   ]

bestlec/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Best20(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    url_lec = models.CharField(max_length= 60)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    grade = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class Finisher(models.Model):
    bestlec = models.ForeignKey(Best20, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.CharField(max_length= 50)
    git_hub = models.CharField(max_length= 80)
    note = models.CharField(max_length= 50)
    created_at = models.DateTimeField(auto_now_add=True)

    def get_insert_url(self):
        return reverse('bestlec:finisher_new', args=[self.bestlec.id])

class RecommandBest20(models.Model):
    bestlec = models.ForeignKey(Best20, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

bestlec/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget
from .models import Best20

class BestLecForm(forms.ModelForm):
    class Meta:
        model = Best20
        fields = ['title', 'description', 'url_lec']

        widgets = {
            'title': forms.TextInput(attrs={'size': 80}),
            'description': SummernoteWidget(),
        }

bestlec/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, UpdateView, CreateView , DeleteView

from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from .models import Best20, Finisher, RecommandBest20
from django.db.models import Q
from django.db.models import F
from django.urls import reverse_lazy
from django.contrib import messages
from django.urls import reverse
from .forms import BestLecForm
from django.contrib.auth.mixins import LoginRequiredMixin



class FinisherDeleteView(DeleteView):
    model = Finisher
    success_url = reverse_lazy('bestlec:best20_list')
    success_message = "finisher is removed"

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(FinisherDeleteView, self).delete(request, *args, **kwargs)

finisher_delete = FinisherDeleteView.as_view()

# 1122
# best20_delete
class Best20DeleteView(DeleteView):
    model = Best20
    success_url = reverse_lazy('bestlec:best20_list')
    success_message = "best is removed"

    def delete(self, request, *args, **kwargs):
            messages.success(self.request, self.success_message)
            return super(Best20DeleteView, self).delete(request, *args, **kwargs)

best20_delete = Best20DeleteView.as_view()


def recommand_lecture(request, id):
    recommand_count = RecommandBest20.objects.filter(Q(bestlec=id)).count()
    print("recommand_count : ", recommand_count)
    bl =  get_object_or_404(Best20, pk=id)

    if recommand_count < 1:
        rc = RecommandBest20.objects.create(author=request.user, bestlec= bl)
        print('추천을 추가')
    else:
        RecommandBest20.objects.filter(bestlec=id).delete()
        print('추천을 삭제')
    return redirect('/bestlec')



class FinisherCreateView(CreateView):
    model = Finisher
    fields = ['comment','git_hub','note']

    def form_valid(self, form):
        print("완료 명단 입력 뷰 실행")
        fn = form.save(commit=False)
        # fn.bestlec = self.kwargs['bl_pk']
        fn.bestlec =  get_object_or_404(Best20, pk=self.kwargs['bl_pk'])
        fn.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        id = self.kwargs['bl_pk']
        return reverse('bestlec:FinisherList', args=[self.kwargs['bl_pk']])

# FinisherList
def FinisherList(request, id):
    fl = Finisher.objects.filter(Q(bestlec=id))
    print("fl : ", fl)
    print('해당 id에 대한 FinisherList')
    return render(request, 'bestlec/finisher_list.html', {
        'fl': fl,
        'fn_id':id
    })

# BestLecDetail
class BestLecDetail(DetailView):
    model = Best20

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(todoDetail, self).get_context_data(**kwargs)
        context['comments'] = CommentForTodo.objects.filter(todo=self.object.pk)
        context['detail_id'] = self.object.pk
        context['comment_form'] = CommentForm()
        return context

def bestlec_new(request):
    if request.method=="POST":
        form = BestLecForm(request.POST, request.FILES)
        if form.is_valid():
            bslec = form.save(commit=False)
            bslec.author = request.user
            bslec.save()
            return redirect('/bestlec')
    else:
        form = BestLecForm()
    return render(request, 'bestlec/bestlec_form.html',{
        'form':form
    })

def grade_plus(request, id):
    Best20.objects.filter(Q(id=id)).update(grade = F('grade') + 1)
    print('grade +1 success')
    return redirect('/bestlec')

class Best20List(LoginRequiredMixin,ListView):
    model = Best20
    paginate_by = 20
    ordering = ['-grade']

bestlec/templates/bestlec/Finisher_form.html
{% extends "layout.html" %}
{%block title %}완료 명단 등록{% endblock %}

{%block content %}
<hr>

<h2>완강 등록</h2>

<hr>

<form action="" method="post">
  {% csrf_token %}
  <table>
    {{form.as_table}}
  </table>
  <input type="submit">
</form>

{% endblock %}

<script type="text/javascript">
{% block extra_js %}



{% endblock %}
</script>

bestlec/templates/bestlec/best20_confirm_delete.html
<form action="" method="post">
  {% csrf_token %}
  <p>정말 삭제 하시겠습니까?</p>
  <input type="submit" value="삭제하세요">
</form>

bestlec/templates/bestlec/best20_list.html
{% extends "layout.html" %}
{%block title %}베스트 강의{% endblock %}

{%block content2 %}

<div class="jumbotron">
    <h2>강의 정보</h2>
</div>

{% if messages %}
<div class="alert alert-success">
    {% for message in messages %}
     {{ message.message }}<strong>{{ message.tags }}</strong>
     {% endfor %}
</div>
{% endif %}

<a href="/bestlec/new/" class="btn btn-danger float-right">입력 </a>

<br><br>

<table class="table table-bordered" id="todo_list">
    <tr>
        <td>index</td>
        <td>title</td>
        <td>완강 목록</td>
        <td>author</td>
        <td>평점</td>
        <td>추천</td>
    </tr>

    {% if object_list.exists %}
        {% for p in object_list %}
            <tr>
                <td>
                    {{ forloop.counter }}
                </td>
                <td>
                    {{p.title}}
                    <a class="badge badge-pill badge-dark btn-sm" href="http://{{p.url_lec}}">site</a>
                    {% if request.user == p.author %}
                        <a class="badge badge-pill badge-primary btn-sm" href="{% url "bestlec:best20_delete" p.id %}">삭제</a>
                    {% endif %}
                </td>
                <td>
                    <button type="button" name="button" onclick="location.href='{{p.id}}/finisherlist'" class="btn btn-outline-info btn-sm">완강({{p.finisher_set.count}})</button>

                </td>
                <td>
                    {{p.author}}
                </td>
                <td>
                    {{ p.recommandbest20_set.count }}
                </td>
                <td>
                    <a class="btn btn-outline-primary btn-sm" href="{% url "bestlec:recommand_lecture" p.pk %}"> 추천 </a>
                </td>
            </tr>
        {% endfor %}
    {% else %}
        <tr>
            <td colspan="4">
                <h4>아직 게시물이 없습니다.</h4>
            </td>
        </tr>
    {% endif %}
</table>


{%endblock%}

<script type="text/javascript">
{% block extra_js %}



{% endblock %}
</script>

bestlec/templates/bestlec/bestlec_form.html
{% extends 'layout.html' %}

{% block content %}

<form method="post" enctype="multipart/form-data">{% csrf_token %}
	<table>
		{{ form.as_table | safe }}
	</table>
	<button type="submit" class="btn btn-primary float-right">Submit</button>
</form>

{{ form.media }}

{% endblock %}

bestlec/templates/bestlec/finisher_confirm_delete.html
<form action="" method="post">
  {% csrf_token %}
  <p>정말 삭제 하시겠습니까?</p>
  <input type="submit" value="삭제하세요">
</form>
    

bestlec/templates/bestlec/finisher_list.html
{% extends "layout.html" %}
{%block title %}todo list{% endblock %}

{%block content %}

<div class="jumbotron">
  <h1>완강자 목록</h1>
  <p>완강자 리스트</p>
</div>

<button
    type="button"
    class="btn btn-outline-info btn-sm float-right"
    name="button" onclick="location.href='/bestlec/{{fn_id}}/finisher/new'"
    >
        post
</button>

<br><br>

<table class="table table-bordered" id="todo_list">
    <tr>
        <td>순번</td>
        <td>author</td>
        <td>comment</td>
        <td>git_hub</td>
        <td>note</td>
        <td>created_at</td>
    </tr>

    {% if fl.exists %}
        {% for p in fl %}
            <tr>
                <td>
                    {{ forloop.counter }}
                </td>
                <td>
                    {{p.author}}
                </td>
                <td>
                    {{p.comment}}

                    {% if request.user == p.author %}
                        <a class="badge badge-pill badge-primary btn-sm" href="{% url "bestlec:finisher_delete" p.id %}">삭제</a>
                    {% endif %}

                </td>
                <td>
                    <a class="btn btn-outline-info" href="{{p.git_hub}}">github</a>
                </td>
                <td>
                    <a class="btn btn-outline-info" href="{{p.note}}">note</a>
                </td>
                <td>
                    {{p.created_at}}
                </td>
            </tr>
        {% endfor %}
    {% else %}
        <tr>
            <td colspan="6">
                <h4>아직 게시물이 없습니다.</h4>
            </td>
        </tr>
    {% endif %}
</table>


{% endblock %}

<script type="text/javascript">
{% block extra_js %}



{% endblock %}
</script>