blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
app_name= 'blog'


urlpatterns = [
    path('', views.PostList.as_view() , name="post_list"),
    path('create/', views.PostCreate.as_view()),
    path('<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    path('category/<str:slug>/', views.PostListByCategory.as_view()),
    path('tag/<str:slug>/', views.PostListByTag.as_view()),
    path('<int:pk>/update/', views.PostUpdate.as_view()),
    path('<int:pk>/new_comment/', views.new_comment),
    path('edit_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('search/<str:q>/', views.PostSearch.as_view()),
    path('<int:pk>/delete/', views.PostDeleteView.as_view() , name='post_delete'),
    path('delete_comment/<int:pk>', views.delete_comment , name='delete_comment'),

]

pd/urls.py
from django.urls import path, re_path , include
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings

app_name = 'pd'

urlpatterns = [
    path('private_task_list/', views.private_task_list.as_view() , name="private_task_list"),
    path('my_task/new/',views.mytask_new , name ="mytask_new"),
    path('delete_mytask_by_ajax/',views.delete_mytask_by_ajax , name ="delete_mytask_by_ajax"),
    path('update_mytask_by_ajax/',views.update_mytask_by_ajax , name ="update_mytask_by_ajax"),
    #
    # path('add_mysite_by_ajax/',views.add_mysite_by_ajax , name ="add_mysite_by_ajax"),
    # path('update_mysite_by_ajax/',views.update_mysite_by_ajax , name ="update_mysite_by_ajax"),
    # path('delete_mysite_by_ajax/',views.delete_mysite_by_ajax , name ="delete_mysite_by_ajax"),

]

reservation_app/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('accounts/', include('accounts2.urls')),
    path('accounts/', include('allauth.urls')),
    # path('logout/', auth_views.LogoutView, name = 'logout', kwargs = {'next_page' : settings.LOGIN_URL}),
    # re_path(r'^logout/$', auth_views.LogoutView, name = 'logout', kwargs = {'next_page' : settings.LOGIN_URL}),
    path('admin/', admin.site.urls),
    path('markdownx/', include('markdownx.urls')),
    path('blog/', include('blog.urls')),
    path('', include('remote_control.urls')),
    path('todo/', include('todo.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('bestlec/', include('bestlec.urls')),
    path('management/', include('management.urls')),
    path('challenge/', include('challenge.urls')),
    path('board/', include('board.urls')),
    path('pd/', include('pd.urls')),
    path('skilblog/', include('skilblog.urls')),
    path('wm/', include('wm.urls')),
    path('skilnote2/', include('skilnote2.urls')),
    path('skilnote3/', include('skilnote3.urls')),
    path('skilnote4/', include('skilnote4.urls')),
]

if settings.DEBUG:
   urlpatterns += static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   import debug_toolbar
   urlpatterns += [
      path ('__debug__/', include (debug_toolbar.urls)),
   ]

wm/urls.py
from django.urls import path, re_path, include
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings

app_name = 'wm'

urlpatterns = [
    # 1122
    path('main_page/', views.main_page.as_view(), name="main_page"),
    path('myshortcut/update_for_permission', views.update_for_permission, name="update_for_permission"),
    path('myshortcut/update_for_start', views.update_for_start, name="update_for_start"),
    path('myshortcut/update_for_end', views.update_for_end, name="update_for_end"),
    
    
    path('myshortcut/joinForOtherMemberNote', views.joinForOtherMemberNote, name="joinForOtherMemberNote"),
    path('myshortcut/cancleForOtherMemberNote', views.cancleForOtherMemberNote, name="joinForOtherMemberNote"),
    
    path('myshortcut/allow_list/<str:skilnote_owner>', views.allow_list.as_view(), name="allow_list"),
    
    path('userlist/loginpage', views.user_list_for_login_page.as_view(),
         name='user_list_for_login_page'),
#     path('', views.SkilNoteListView.as_view(), name="my_shortcut_list"),
    path('', views.main_page.as_view(), name="main_page"),
    path('myshortcut/search_skil_note_for_me/',
         views.search_skil_note_for_me.as_view(), name="search_skil_note_for_me"),
    path('myshortcut/search_skil_note_for_all/',
         views.search_skil_note_for_all.as_view(), name="search_skil_note_for_all"),
    path('myshortcut/search_skilnote_by_file_name_for_me/',
         views.search_skilnote_by_file_name_for_me.as_view(), name="search_skilnote_by_file_name_for_me"),
    path('myshortcut/search_skilnote_by_file_name_for_all/',
         views.search_skilnote_by_file_name_for_all.as_view(), name="search_skilnote_by_file_name_for_all"),
    
    path('myshortcut/copy_chapter_to_x/',
         views.copy_chapter_to_x, name='copy_chapter_to_x'),     
    
    path('myshortcut/copy_to_me_from_user_id/',
         views.copy_to_me_from_user_id, name='copy_to_me_from_user_id'),
   
    
    
    
    path('myshortcut/', views.SkilNoteListView.as_view(), name="my_shortcut_list"),
    path('myshortcut2/', views.MyShortCutListView2.as_view(),
         name="my_shortcut_list2"),
    path('myshortcut/insert_temp_skill_note_for_textarea/', views.insert_temp_skill_note_for_textarea,
         name="insert_temp_skill_note_for_textarea"),  # mini note insert front
    path('myshortcut/insert_for_guest_book/', views.insert_for_guest_book,
         name="insert_for_guest_book"),  # geust book insert
    path('myshortcut/guest_book_list/<str:guest_book_owner>',
         views.guest_book_list, name="guest_book_list"),  # guest_book_list
    path('myshortcut/delete_guest_book_list/<int:id>',
         views.delete_guest_book_list, name="delete_guest_book_list"),
    path('myshortcut/delete_comment_for_skilpage/<int:id>',
         views.delete_comment_for_skilpage, name="delete_comment_for_skilpage"),
    path('myshortcut/temp_skill_list_for_backend/<page_user>',
         views.temp_skill_list_for_backend2, name="temp_skill_list_for_backend"),
    path('myshortcut/temp_skill_list/<page_user>', views.temp_skill_list2,
         name="temp_skill_list"),  # mininote for frontend
    path('myshortcut/temp_skill_list_for_backend',
         views.temp_skill_list_for_backend1, name="temp_skill_list_for_backend"),
    path('myshortcut/temp_skill_list', views.temp_skill_list1,
         name="temp_skill_list"),  # mininote for frontend
    path('myshortcut/temp_skill_list_for_backend/',
         views.temp_skill_list_for_backend1, name="temp_skill_list_for_backend"),
    path('myshortcut/temp_skill_list/', views.temp_skill_list1,
         name="temp_skill_list"),  # mininote for frontend
    path('new_comment_for_skilpage/<str:user_name>/<str:category_id>/',
         views.new_comment_for_skilpage, name="new_comment_for_skilpage"),
    path('manual', views.manualPage, name="manual"),
    
    path('myshortcut/update_skil_note_file_name/<int:id>',
         views.update_skil_note_file_name, name="update_skil_note_file_name"),
    

    path('myshortcut/category_plus_1_for_current_user',
         views.category_plus_1_for_current_user, name='category_plus_1_for_current_user'),
    path('myshortcut/category_minus_1_for_current_user',
         views.category_minus_1_for_current_user, name='category_minus_1_for_current_user'),
    path('myshortcut/move_to_skil_blog/',
         views.move_to_skil_blog, name='move_to_skil_blog'),
    path('myshortcut/plus_recommand_for_skillnote_user/',
         views.plus_recommand_for_skillnote_user, name='plus_recommand_for_skillnote_user'),
    path('myshortcut/edit_complete_skill_note_for_front_end/<int:id>',
         views.edit_complete_skill_note_for_front_end, name='edit_complete_skill_note_for_front_end'),
    path('myshortcut/edit_complete_skill_note_for_backend/<int:id>',
         views.edit_complete_skill_note_for_backend, name='edit_complete_skill_note_for_backend'),
    path('myshortcut/edit_temp_skill_note_using_textarea_for_backend/<int:id>',
         views.edit_temp_skill_note_using_textarea_for_backend, name='edit_temp_skill_note_using_textarea_for_backend'),
    path('myshortcut/edit_temp_skill_note_using_input_for_backend/<int:id>',
         views.edit_temp_skill_note_using_input_for_backend, name='edit_temp_skill_note_using_input_for_backend'),
    path('myshortcut/update_temp_skil_title_for_backend/<int:id>',
         views.update_temp_skil_title_for_backend, name="update_temp_skil_title_for_backend"),
    path('myshortcut/delete_temp_skill_note_for_backendarea/<int:id>',
         views.delete_temp_skill_note_for_backendarea, name="delete_temp_skill_note_for_backendarea"),
    path('myshortcut/insert_temp_skill_note_using_input_for_backend/',
         views.insert_temp_skill_note_using_input_for_backend, name="insert_temp_skill_note_using_input_for_backend"),
    path('myshortcut/insert_temp_skill_note_using_textarea_for_backend/',
         views.insert_temp_skill_note_using_textarea_for_backend, name="insert_temp_skill_note_using_textarea_for_backend"),
    path('myshortcut/insert_temp_skill_note_for_input/',
         views.insert_temp_skill_note_for_input, name="insert_temp_skill_note_for_input"),
    path('myshortcut/edit_temp_skill_note_for_input/<int:id>',
         views.edit_temp_skill_note_for_input, name='edit_temp_skill_note_for_input'),
    path('myshortcut/update_temp_skill_note_for_textarea/<int:id>',
         views.update_temp_skill_note_for_textarea, name='update_temp_skill_note_for_textarea'),
    path('myshortcut/update_temp_skil_title/<int:id>',
         views.update_temp_skil_title, name="update_temp_skil_title"),
    path('myshortcut/delete_temp_memo_by_ajax/<int:id>',
         views.delete_temp_memo_by_ajax, name="delete_temp_memo_by_ajax"),

    path('myshortcut/search_by_id_and_word/',
         views.searchSkilNoteViewByIdAndWord, name="search_by_id_and_word"),

    path('myshortcut/copyForCategorySubjectToMyCategory/',
         views.copyForCategorySubjectToMyCategory, name="copyForCategorySubjectToMyCategory"),
    path('new_comment_for_my_shortcut/<int:shortcut_id>/ajax/',
         views.new_comment_for_my_shortcut, name="new_comment_for_my_shortcut"),
    path('update_shortcut_comment_ajax/<int:shortcut_comment_id>',
         views.update_comment_for_my_shortcut, name="update_comment_for_my_shortcut"),
    path('delete_shortcut_comment_ajax/<int:shortcut_comment_id>',
         views.delete_comment_for_my_shortcut, name="delete_comment_for_my_shortcut"),
    path('myshortcut/update/shortcut_subject/',
         views.update_my_shortcut_subject, name="update_my_shortcut_subject"),
    path('myshortcut/create_input_first/',
         views.create_input_first, name="create_new1_input_first"),
    path('myshortcut/create_textarea_first/',
         views.create_textarea_first, name="create_new2_textarea_first"),
    path('myshortcut/create_summernote_first/',
         views.create_summernote_first, name="create_summernote_first"),
    path('myshortcut2/create_input_first/',
         views.create_input_first, name="create_new1_input_first"),
    path('myshortcut2/create_textarea_first/',
         views.create_textarea_first, name="create_new2_textarea_first"),
    path('myshortcut2/create_summernote_first/',
         views.create_summernote_first, name="create_summernote_first"),
    path('myshortcut/create_new1_input/ajax/',
         views.create_new1_input, name="create_new1_input"),
    path('myshortcut/create_new2_textarea/ajax/',
         views.create_new2_textarea, name="create_new2_textarea"),
    path('myshortcut/create_new1_input_between/ajax/<int:current_article_id>',
         views.create_new1_input_between, name="create_new1_input_between"),
    path('myshortcut/create_new2_textarea_between/ajax/<int:current_article_id>',
         views.create_new2_textarea_between, name="create_new2_textarea_between"),
    path('myshortcut/create_new4_textarea/ajax/',
         views.create_new4_textarea, name="create_new4_textareas"),
    path('myshortcut/update/category/nick/',
         views.update_shortcut_nick, name="update_category_nick"),
    path('myshortcut/update/category_nick_by_author/',
         views.update_shortcut_nick2, name="update_category_nick2"),
    path('new/input', views.MyShortCutCreateView_input.as_view(),
         name="insert_myshortcut_input"),
    path('new/input_title/', views.MyShortCutCreateView_image.as_view(),
         name="MyShortCutCreateView_image"),
    path('new/textarea', views.MyShortCutCreateView_textarea.as_view(),
         name="insert_myshortcut_textarea"),
    path('new/textarea_summer_note', views.CreateSkilNoteBySummerNote.as_view(),
         name="insert_myshortcut_textarea_summer_note"),


    # 220111 고치고 있음
    path('myshortcut/createSkilNoteForInsertMode/',
         views.createSkilNoteForInsertMode.as_view(), name="createSkilNoteForInsertMode"),
    path('myshortcut/InsertForOtherUserNote/<int:category_num>',

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from markdownx.models import MarkdownxField
from markdownx.utils import markdown

# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=40, unique=True)
    slug = models.SlugField(unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return '/blog/tag/{}/'.format(self.slug)

class Category(models.Model):
    name = models.CharField(max_length=25, unique=True)
    description = models.TextField(blank=True)
    slug = models.SlugField(unique=True, allow_unicode=True)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return '/blog/category/{}/'.format(self.slug)


class Post(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField(blank=True)
    head_image = models.ImageField(upload_to='blog/%y%m%d', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, blank=True, null=True, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, blank=True)

    def get_markdown_content(self):
        return markdown(self.content)

    def __str__(self):
        return '{}::{}'.format(self.title, self.author)

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.id])

    def get_update_url(self):
        return self.get_absolute_url() + 'update/'


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = MarkdownxField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def get_markdown_content(self):
        return markdown(self.text)

    def get_absolute_url(self):
        return self.post.get_absolute_url() + '#comment-id-{}'.format(self.pk)

blog/forms.py
from .models import Comment
from django import forms
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget
from .models import Post


class PostingFormForPost(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','content','head_image','category','tags']

        widgets = {
            'title': forms.TextInput(attrs={'size': 100}),
            'content': SummernoteWidget(attrs={'summernote': {'width': '100%', 'height': '400px', 'line-height': 1.2, 'font-size':12, 'tabSize': 4, "backcolor":"white", 'color':"white", 'backColor' :'white' , "maximumImageFileSize": "5242880"  }}),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

blog/templates/blog/_post_list.html
{% load static %}
{%block title %}tech news{% endblock %}
{%block content %}

<style>
  table {
    width: 100%;
    border: 1px solid #444444;
    border-collapse: collapse;
  }
  th, td {
    border: 1px solid #444444;
    padding: 10px;
  }
</style>

<!-- Blog Post -->
<div class="container" id="main-div2">
    <br>
    {% if object_list.exists%}
        {% for p in object_list %}
        <table>
            <tr>
                <td>
                    <a href="{{p.get_absolute_url}}">
                        {{p.title}}
                    </a>
                </td>
            </tr>
            <tr>
                <td>{{p.content | truncatewords:50}}</td>
            </tr>
        </table>
        <hr>

        {% if request.user == p.author %}
            <a href="{% url "blog:post_delete" p.pk %}" class="btn btn-outline-dark">삭제</a>
        {% endif %}

        {% endfor %}
    {% else %}
        <h4>아직 게시물이 없습니다.</h4>
    {% endif %}


</div>

<hr>
{% if is_paginated %}
<!-- Pagination -->
<ul class="pagination justify-content-center mb-4">
    {% if page_obj.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">&larr; Older</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#">&larr; Older</a>
    </li>
    {% endif %}

    {% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Newer &rarr;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#">Newer &rarr;</a>
    </li>
    {% endif %}
</ul>
{% endif %}


{% endblock %}

blog/templates/blog/layout.html
{% extends "layout.html" %}

{%block sidearea %}

<!-- Sidebar Widgets Column -->
  <!-- Search Widget -->
  <div class="card my-4">
    <h5 class="card-header">Search</h5>
    <div class="card-body">
      <div class="input-group">
        <!-- <input type="text" class="form-control" placeholder="Search for..."> -->
        <input type="text" id="search-input" onkeyup="wait_for_enterkey()" class="form-control" placeholder="Search for..."/>

        <span class="input-group-btn">
          <!-- <button class="btn btn-secondary" type="button">Go!</button> -->
          <button class="btn btn-secondary" type="button" onclick="search_post();">Go!</button>

        </span>
      </div>
    </div>
  </div>

  <!-- Categories Widget -->
  <div class="card my-4" id="category-card">
    <h5 class="card-header">Categories</h5>
    <div class="card-body">
      <div class="row">
        <div class="col-lg-12">
            <ul>
                <li>
                    <a href="/blog/category/_none/">미분류 ({{ posts_without_category }})</a>
                </li>
                {% for category in category_list %}
                <li>
                    <a href="{{category.get_absolute_url}}">{{ category.name }} ({{ category.post_set.count }})</a>
                </li>
                {% endfor %}
            </ul>
        </div>
      </div>
    </div>
  </div>

  <!-- Side Widget -->
  <div class="card my-4">
    <h5 class="card-header">메뉴 소개    </h5>
    <div class="card-body">
      it tech & news
    </div>
</div>


{%endblock%}

blog/templates/blog/post_confirm_delete.html
<form action="" method="post">
  {% csrf_token %}
  <p>정말 삭제 하시겠습니까?</p>
  <input type="submit" value="삭제하세요">
</form>

blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}
{% load static %}
{% load crispy_forms_tags %}

{%block title %}블로그 상세보기{% endblock %}
{%block content %}

    <!-- Blog Detail -->
    <!-- Preview Image -->
    {% if object.head_image %}
        <img class="img-fluid rounded" src="{{ object.head_image.url }}" alt="{{ object.title }}">
    {% endif %}

    <h1>{{ object.title }}</h1>
    {% if object.category %}
        <span class="badge badge-primary float-right">{{ object.category }}</span>
    {% else %}
        <span class="badge badge-primary float-right">미분류</span>
    {% endif %}
    <div>
        {{ object.content | safe }}
    </div>
    <!-- Author -->
    <p class="lead">
        by
        <a href="#">{{ object.author.username }}</a>
    </p>
    <br/>
    <br>
    <!-- EDIT -->
    <!-- {{object.author}} -->
    {% if request.user == object.author %}
        <button type="button" class="btn btn-sm btn-outline-secondary float-right" onclick=location.href='{% url "blog:post_list"  %}'>목록</button>
        <button type="button" class="btn btn-sm btn-outline-secondary float-right" onclick=location.href='{% url "blog:post_delete" object.id %}'>삭제</button>
        <button type="button" class="btn btn-sm btn-outline-secondary float-right" onclick=location.href='{{ object.get_update_url }}'>EDIT</button>
    {% endif %}

    {% for tag in object.tags.all %}
        <a href="{{ tag.get_absolute_url }}">#{{ tag }}</a>
    {% endfor %}
    <hr>

    {% if user.is_authenticated %}
        <div class="card my-4">
            <h5 class="card-header">Leave a Comment:</h5>
            <div class="card-body">
                <form method="post" action="{{ object.get_absolute_url }}new_comment/">{% csrf_token %}
                    <div class="form-group">
                        {{ comment_form | crispy }}
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    {% else  %}
        <button type="button" class="btn btn-primary btn-lg btn-block" onclick="location.href='/accounts/login'"> 로그인 </button>
    {% endif %}

    <!-- post_detail 댓글 영역 -->
    <div id="comment-list">
        {% for comment in object.comment_set.all %}
            <div class="media mb-4" id="comment-id-{{ comment.pk }}">
                <!-- <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt=""> -->
                {% if comment.author.socialaccount_set.all.0.get_avatar_url %}
                <img width="50px" class="d-flex mr-3 rounded-circle" src="{{ comment.author.socialaccount_set.all.0.get_avatar_url }}" alt="">
                {% else %}
                    <img width="50px" class="d-flex mr-3 rounded-circle" src="https://api.adorable.io/avatars/285/{{ comment.author }}.png" alt="">
                {% endif %}

                <div class="media-body">
                    <!-- 버튼 영역 -->
                    {% if comment.author == request.user %}
                        <button class="btn btn-sm btn-info float-right" onclick="location.href='/blog/edit_comment/{{ comment.pk }}/'">
                                edit
                        </button>
                        <button class="btn btn-sm btn-warning float-right" data-toggle="modal" data-target="#deleteCommentModal-{{ comment.pk }}">
                                delete
                        </button>
                    {% endif %}
                    <h5 class="mt-0">
                        {{ comment.author }}
                        <small class="text-muted">{{ comment.created_at }}</small>
                    </h5>
                    {{ comment.get_markdown_content | safe }}
                </div>
            </div>
        {% endfor %}
    </div>

    <!-- 댓글 삭제 모달  -->
    {% for comment in object.comment_set.all %}
        {% if user == comment.author %}
            <div class="modal fade" id="deleteCommentModal-{{ comment.pk }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">정말로 삭제하시겠습니까?</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>{{ comment.get_markdown_content | safe  }}</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary" onclick="location.href='/blog/delete_comment/{{comment.pk}}'">Delete</button>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endfor %}

{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/layout.html" %}
{% load static %}
{% load bootstrap4 %}

{%block title %} 사이드 프로젝트 & 구인 구직 {% endblock %}
{%block content %}
<br><br>

<div class="container mt-2" id="main-div2">
    {% if user.is_authenticated %}
        <button
                class="btn btn-primary btn-sm float-right"
                onclick="location.href='/blog/create/'"
        >
            New Post
        </button>
    {% endif %}
    <br>
    <h1 class="mt-4" id="blog-list-title">
        {% if category %}
            <small class="text-muted">: {{ category }}</small>
        {% endif %}
        {% if tag %}
            <small class="text-muted">: #{{ tag }}</small>
        {% endif %}
    </h1>

    <div id="post_list" class="mt-2">
        {% if object_list.exists%}
            {% for p in object_list %}
                <div class="card mb-4" id="post-card-{{ p.pk }}">
                    {% if p.head_image %}
                        <img class="card-img-top" src={{ p.head_image.url }} alt="Card image cap">
                    {% else %}
                        <img class="card-img-top" src="https://picsum.photos/700/300/?random" alt="Card image cap">
                    {% endif %}
                    <div class="card-body">
                        {% if p.category %}
                            <span class="badge badge-primary float-right">{{ p.category }}</span>
                        {% else %}
                            <span class="badge badge-primary float-right">미분류</span>
                        {% endif %}
                        <h2 class="card-title">{{p.title}}</h2>
                        <p class="card-text">
                            {{p.content | truncatewords:50}}
                        </p>
                        {% for tag in p.tags.all %}
                            <a href="{{ tag.get_absolute_url }}">#{{ tag }} </a>
                        {% endfor %}
                        <br/>
                        <br/>
                        <a href="{{p.get_absolute_url}}" class="btn btn-primary">Read More &rarr;</a>

                        {% if request.user == p.author %}
                            <a href={% url 'blog:post_delete' p.pk %} class="btn btn-outline-dark">삭제</a>
                        {% endif %}
                    </div>
                    <div class="card-footer text-muted">
                        Posted on {{p.created}} {{p.author}}
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h4>아직 게시물이 없습니다.</h4>
        {% endif %}
        </div>
    </div>
    <hr>

    {% if is_paginated %}
        {% bootstrap_pagination page_obj size="small" justify_content="center" %}
    {% endif %}

{% endblock %}

<script type="text/javascript">
    {%block extra_js %}

    // $(document).ready(function(){
    //     //scroll을 구현해 보자
    //     console.log("scroll event for post_list");
    //     $win = $(window);
    //     var is_loaded = false;
    //     var current_page;
    //     $win.scroll(() => {
    //         var diff = $(document).height() - $win.height();
    //
    //         if((!is_loaded) && diff - $win.scrollTop() < 1 ) {
    //             console.log("현재 창의 위치는 바닥입니다.");
    //             var next_page = (current_page || 1) + 1;
    //             current_page = next_page
    //             var next_page_url = '?page=' + next_page;
    //             is_loaded = true;
    //             $.get(next_page_url).
    //             done(function(html) {
    //                 console.log("html(next) : ", html)
    //                 $("#post_list").append(html);
    //                 next_page = current_page +1
    //                 console.log("현재 페이지 번호 : ", current_page);
    //             }).
    //             fail(function(hxr, textStatus, error) {
    //                 console.log(textStatus);
    //             }).always(function() {
    //                 console.log("always");
    //                 is_loaded = false;
    //             });
    //         }
    //     });
    // })

    {% endblock %}
</script>