pd/urls.py
from django.urls import path, re_path , include
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings

app_name = 'pd'

urlpatterns = [
    path('private_task_list/', views.private_task_list.as_view() , name="private_task_list"),
    path('my_task/new/',views.mytask_new , name ="mytask_new"),
    path('delete_mytask_by_ajax/',views.delete_mytask_by_ajax , name ="delete_mytask_by_ajax"),
    path('update_mytask_by_ajax/',views.update_mytask_by_ajax , name ="update_mytask_by_ajax"),
    #
    # path('add_mysite_by_ajax/',views.add_mysite_by_ajax , name ="add_mysite_by_ajax"),
    # path('update_mysite_by_ajax/',views.update_mysite_by_ajax , name ="update_mysite_by_ajax"),
    # path('delete_mysite_by_ajax/',views.delete_mysite_by_ajax , name ="delete_mysite_by_ajax"),

]

reservation_app/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('accounts/', include('accounts2.urls')),
    path('accounts/', include('allauth.urls')),
    # path('logout/', auth_views.LogoutView, name = 'logout', kwargs = {'next_page' : settings.LOGIN_URL}),
    # re_path(r'^logout/$', auth_views.LogoutView, name = 'logout', kwargs = {'next_page' : settings.LOGIN_URL}),
    path('admin/', admin.site.urls),
    path('markdownx/', include('markdownx.urls')),
    path('blog/', include('blog.urls')),
    path('', include('remote_control.urls')),
    path('todo/', include('todo.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('bestlec/', include('bestlec.urls')),
    path('management/', include('management.urls')),
    path('challenge/', include('challenge.urls')),
    path('board/', include('board.urls')),
    path('pd/', include('pd.urls')),
    path('skilblog/', include('skilblog.urls')),
    path('wm/', include('wm.urls')),
    path('skilnote2/', include('skilnote2.urls')),
    path('skilnote3/', include('skilnote3.urls')),
    path('skilnote4/', include('skilnote4.urls')),
]

if settings.DEBUG:
   urlpatterns += static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   import debug_toolbar
   urlpatterns += [
      path ('__debug__/', include (debug_toolbar.urls)),
   ]

todo/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name= 'todo'
urlpatterns = [

    # 할 일(미완료 ) 리스트 출력
    path('', views.TodoList.as_view() , name="todo_list"),

    # 할 일 (완료) 리스트 출력
    path('todolist/complete/me/', views.TodoCompleteListByMe.as_view() , name="todo_complete_list_byme"),

    # todolist detail popup 출력
    path('<int:pk>/', views.todoDetail.as_view(), name='todo_detail'),


    path('team_todo_list/pass_task_to_selected_user/', views.pass_task_to_selected_user, name="pass_task_to_selected_user"),

    path('add_todo_by_ajax/', views.add_todo_by_ajax, name="add_todo_by_ajax"),
    path('add_todo_for_team_by_ajax/', views.add_todo_for_team_by_ajax, name="add_todo_for_team_by_ajax"),
    path('add_todo_by_ajax_by_teamleader/', views.add_todo_by_ajax_by_teamleader, name="add_todo_by_ajax_by_teamleader"),

    path('team_info_list/', views.TeamInfoListView.as_view() , name="TeamInfoListView"),

    path('team_todo_list/<str:team_name>', views.team_todo_list , name="team_todo_list"),
    path('team_todo_list_by_check_user/<str:team_name>', views.team_todo_list_by_check_user , name="team_todo_list_by_check_user"),

    path('TeaminfoCreate/', views.TeamInfoCreateView.as_view() , name="create_team_info"),
    # 팀 리스트 삭제
    path('team_info_list/delete/teaminfo/<int:team_id>', views.delete_team_info , name="delete_team_info"),
    path('<int:id>/edit/', views.todo_edit, name='todo_edit'),
    path('<int:pk>/delete/', views.todo_delete, name='todo_delete'),
    path('new/',views.todo_new , name ="todo_new"),
    path('search/<str:q>/', views.TodoSearch.as_view()),
    path('card', views.TodoList_by_card.as_view() , name="todo_list_by_card"),

    path('complete_bycard/', views.TodoListByComplete_by_card.as_view() , name="todo_complete_list_by_card"),
    # path('<int:pk>/new_comment/summer_note', views.new_comment_summer_note),
    path('<int:pk>/new_comment_by_summer_note', views.new_comment_by_summer_note, name="new_comment_by_summer_note"),

    path('<int:pk>/new_comment/text_area', views.new_comment_text_area),
    path('edit_comment/<int:pk>/', views.CommentUpdate.as_view(), name="edit_url"),
    path('delete_comment/<int:pk>/', views.delete_comment, name="delete_url"),
    path('<int:id>/todo_complete/',views.todo_complete , name ="todo_complete"),
    path('<int:id>/todo_help/', views.todo_help, name="todo_help"),
    path('<int:id>/todo_help_cancle/', views.todo_help_cancle, name="todo_help_cancle"),
    path('category/<str:slug>/', views.TodoListByCategory.as_view() , name="total_ucomplete_todo_list"),
    path('todolist/admin/', views.TodoListByAdmin.as_view() , name="todo_list_by_admin"),
    path('todolist/admin/insert_popup/<str:user_name>', views.isnert_todo_popup_by_admin , name="isnert_todo_popup_by_admin"),


    path('todolist/complete/me/todo_delete_ajax/', views.todo_delete_ajax , name="todo_delete_ajax"),
    path('todolist/uncomplete/me', views.TodoUnCompleteListByMe.as_view() , name="todo_uncomplete_list_byme"),
    path('completeList/total/', views.TodoListByComplete_total.as_view() , name="todo_complete_list_total"),

    path('update_comment_ajax/summernote/<int:id>', views.update_comment_ajax_for_summernote , name='update_comment_ajax'),
    path('update_comment_ajax/textarea/<int:id>', views.update_comment_ajax_for_textarea , name='update_comment_ajax'),


    path('delete_comment_ajax/<int:id>', views.delete_comment_ajax , name='delete_comment_ajax'),
    path('<int:pk>/update/', views.CommentUpdate.as_view()),
    path('new/admin/<str:user_name>/<str:leader_name>/',views.todo_new_admin, name ="todo_new_admin"),
    path('status/',views.todo_status_list, name ="todo_status_list"),
    path('todo_delete_ajax/',views.todo_delete_ajax, name ="todo_delete_ajax"),
    path('todolist/uncomplete/<str:user_id>/',views.UncompleteTodoListByUserId.as_view(), name ="TodoListByUserId"),
    path('todolist/complete/<str:user_id>/',views.CompleteTodoListByUserId.as_view(), name ="TodoListByUserId"),

    path('todolist/uncomplete/admin/<str:user_id>/<str:team_leader_name>',views.UncompleteTodoListByUserId_admin.as_view(), name ="todolist_by_user_complete"),
    path('todolist/complete/admin/<str:user_id>/<str:team_leader_name>',views.CompleteTodoListByUserId_admin.as_view(), name ="todolist_by_user_uncomplete"),

    # team
    path('team_register/', views.team_register , name='team_register'),
    path('withdrawl_team/', views.withdrawl_team , name='withdrawl_team'),
    path('team_member_list/<int:team_info_id>/delete/team/memeber', views.delete_team_member, name='delete_team_member'),
    path('delete/team/memeber/byajax', views.delete_team_memeber_info_by_memberId, name="delete_team_memeber_info_by_memberId"),

    path('team_member_list/<int:team_info_id>', views.team_member_list_view.as_view() , name="team_member_list"),



]

todo/models.py
from django.db import models
from django.contrib.auth.models import User
# from datetime import datetime
from django.utils import timezone
from markdownx.models import MarkdownxField
from markdownx.utils import markdown
from django.urls import reverse
# from datetime import timedelta
from datetime import datetime, timedelta


class TeamInfo(models.Model):
    leader = models.ForeignKey(User, on_delete=models.CASCADE)
    team_name = models.CharField(max_length=50, unique=True)
    team_description = models.TextField(blank=True)
    member_count = models.IntegerField(default=1)

    def __str__(self):
        return self.team_name

class TeamMember(models.Model):
    team = models.ForeignKey(TeamInfo, on_delete=models.CASCADE)
    member = models.ForeignKey(User, on_delete=models.CASCADE)
    position = models.CharField(max_length=50,default="member")


class Classification(models.Model):
    name = models.CharField(max_length=25, unique=True)
    description = models.TextField(blank=True)
    slug = models.SlugField(unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'classifications'

class Category(models.Model):
    name = models.CharField(max_length=25, unique=True)
    description = models.TextField(blank=True)
    slug = models.SlugField(unique=True, allow_unicode=True)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = 'categories'
    def get_absolute_url(self):
        return '/todo/category/{}/'.format(self.slug)

class TodoType(models.Model):
    type_name = models.CharField(max_length=20)

    def __str__(self):
        return self.type_name

def utc_tomorrow():
    return datetime.now() + timedelta(days=1)

class Todo(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField(blank=True)
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    dead_line = models.DateTimeField(blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    elapsed_time = models.CharField(max_length=20,blank=True, null=True)
    category = models.ForeignKey(Category, blank=True, null=True, on_delete=models.CASCADE)
    classification = models.ForeignKey(Classification, blank=True, null=True, on_delete=models.CASCADE, default=2)
    completion = models.CharField(max_length=10, default='uncomplete')
    importance = models.IntegerField(default=1)
    type= models.ForeignKey(TodoType, on_delete=models.CASCADE, default=2)
    director = models.CharField(max_length=40, default="terecal")

    def __str__(self):
        return self.title

    def get_markdown_content(self):
        return markdown(self.content)

    def now_diff(self):
        delta = timezone.now() - self.created
        return str(delta - timedelta(microseconds=delta.microseconds))

    def remaining_time(self):
        delta = self.dead_line - timezone.now()
        return str(delta - timedelta(microseconds=delta.microseconds))

    def get_absolute_url(self):
        return reverse('todo:todo_detail', args=[self.id])

class CommentForTodo(models.Model):
    todo= models.ForeignKey(Todo, on_delete=models.CASCADE)
    title= models.CharField(max_length=60)
    file_name = models.CharField(max_length= 60)
    text = models.TextField()
    text_type = models.CharField(max_length=20, blank=True, default="summer_note")
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    type= models.ForeignKey(TodoType, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    user_type = models.IntegerField(blank=True,default=1)

    def get_markdown_content(self):
        return markdown(self.text)

    def get_absolute_url(self):
        return reverse('todo:todo_list')

todo/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Todo, CommentForTodo

from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget
from django.contrib.admin import widgets

import datetime

class TodoForm(forms.ModelForm):

    dead_line = forms.SplitDateTimeField(widget=widgets.AdminSplitDateTime, initial=datetime.datetime.now())

    class Meta:
        model = Todo

        fields = ['title', 'content','classification','dead_line']
        widgets = {
            'title': forms.TextInput(attrs={'size': 80}),
            'content': SummernoteWidget(),
        }

class TodoAdminForm(forms.ModelForm):
    dead_line = forms.SplitDateTimeField(widget=widgets.AdminSplitDateTime , initial=datetime.datetime.now())

    class Meta:
        model = Todo
        fields = ['classification','title', 'content','dead_line']

        widgets = {
            'title': forms.TextInput(attrs={'size': 80}),
            'content': SummernoteWidget(),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = CommentForTodo
        fields = ('title','file_name','text')

        widgets = {
            'title': forms.TextInput(attrs={'size': 65}),
            'file_name': forms.TextInput(attrs={'size': 65}),
            'text': SummernoteWidget(attrs={'summernote': {'width': '100%', 'iframe': False, "dialogsInBody":False}}),
        }

class CommentForm_TextArea(forms.ModelForm):
    class Meta:
        model = CommentForTodo
        fields = ('title','file_name','text')

todo/templates/todo/insert_todo_form_by_admin.html
{% extends 'layout.html' %}

{% load crispy_forms_tags %}

{% block content %}

<h4 >user: <span class="text-primary">{{ user_name }}</span></h4>

<form method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form | safe }}

	<button type="submit" class="btn btn-primary float-right">Submit</button>

</form>

{{ form.media }}

{% endblock %}

todo/templates/todo/post_form.html
{% extends 'layout.html' %}

{% load crispy_forms_tags %}

{% block content %}

<h2>todo 입력</h2>

<form method="post" enctype="multipart/form-data">
	{% csrf_token %}

	{{ form | safe }}

	<button type="submit" class="btn btn-primary float-right btn-block">Submit</button>

</form>

{{ form.media }}


{% endblock %}

todo/templates/todo/team_todo_list_by_check_user.html
<table class="table table-bordered" id="todo_list">
    <tr>
        <td>check</td>
        <td>classification</td>
        <td>author</td>
        <td>title</td>
        <td>남은 시간</td>
        <td>마감 기한</td>
    </tr>

    {% if team_todo_list.exists %}
    {% for p in team_todo_list %}
    <tr>
        <td>
            <input type="checkbox" id="{{p.pk}}" class="td_check">
        </td>
        <td>{{p.classification}}</td>
        <td>{{p.author}}</td>
        <td>
            <a href="" id={{p.id}} class="title_for_list">
                {{p.title}} (<font color="blue"> from {{p.director}}</font> )
            </a><br>
            <a class="badge badge-pill badge-dark" href="{% url "todo:todo_edit" p.id %}">수정</a>
        </td>
        <td>
            {% if p.dead_line %}
            {{p.remaining_time}}
            {% else %}
            {% endif %}
        </td>
        <td>{{p.dead_line}}</td>
    </tr>
    {% endfor %}
    <tbody id="tbody_todo"></tbody>
    {% else %}
    <tr>
        <td colspan="5">
            <h4>아직 게시물이 없습니다.</h4>
        </td>
    </tr>
    {% endif %}

</table>

todo/templates/todo/todo_list_by_card.html
{% extends "todo/layout.html" %}
{%block title %}Blog{% endblock %}
{%block content %}

<br>
<h2>할일 목록(admin)</h2>

{% if object_list.exists%}
    {% for p in object_list %}
        <table class="table table-bordered">
            <tr>
                <td style="width: 20%">작성자</td>
                <td>{{p.author}}</td>
            </tr>
            <tr>
                <td style="width: 20%">title</td>
                <td>{{p.title}}</td>
            </tr>
            <tr>
                <td style="width: 20%">content</td>
                <td>{{p.content}}</td>
            </tr>
            <tr>
                <td style="width: 20%">note</td>
                <td>
                    <a href="https://{{p.note}}">note</a>
                </td>
            </tr>
            <tr>
                <td>시작 시간</td>
                <td>{{p.created}}</td>
            </tr>
            <tr>
                <td>경과 시간</td>
                <td>{{p.now_diff}}</td>
            </tr>
            <tr>
                <td colspan="2">
                    {% if request.user == p.author %}
                        <button type="button" class="btn btn btn-outline-danger btn-sm float-right" onclick="updateTodo(this.id)">
            				<a href="{% url "todo:todo_complete" p.id %}" class="" data-target-id="" data-message="">
                                완료
                            </a>
                        </button>

                        <button type="button" class="btn btn btn-outline-danger btn-sm float-right" onclick="updateTodo(this.id)">
            				<a href="{% url "todo:todo_delete" p.pk %}" class="" data-target-id="" data-message="">
                                삭제
                            </a>
                        </button>

                        <button type="button" class="btn btn btn-outline-danger btn-sm float-right" onclick="updateTodo(this.id)">
            				<a href="{% url "todo:todo_edit" p.id %}" class="" data-target-id="" data-message="">
                                수정
                            </a>
                        </button>
                    {% endif %}
                </td>
            </tr>
        </table>
    {% endfor %}

    <!-- 페이지 네이션 start -->
    {% if is_paginated %}
        <!-- Pagination -->
        <ul class="pagination justify-content-center mb-4">
            {% if page_obj.has_next %}
            <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">&larr; Older</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                    <a class="page-link" href="#">&larr; Older</a>
            </li>
            {% endif %}

            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Newer &rarr;</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">Newer &rarr;</a>
            </li>
            {% endif %}
        </ul>
    {% endif %} <!-- 페이지 네이션 end -->
    <hr>
{% else %}
    <h4>아직 게시물이 없습니다.</h4>
{% endif %}


<script type="text/javascript">
    // modal 이벤트 : 상세 보기
    $(document).on('click', '.recommand_button', function (e) {
        e.preventDefault();
        var href = $(this).attr("href");
		alert(href);
</script>


{% endblock %}

todo/templates/todo/todo_list_complete.html
{% extends "todo/layout.html" %}
{%block title %}todo complete (me){% endblock %}

{%block extra_css %}

.modal-dialog {
  width: 100%;
  height: 50%;
  margin: 0;
  padding: 0;
}

.modal-content {
    width:132%;
}

{% endblock %}

{%block content5 %}
{% load crispy_forms_tags %}

{% if messages %}
<div class="alert alert-success">
    {% for message in messages %}
     {{ message.message }}<strong>{{ message.tags }}</strong>
     {% endfor %}
</div>
{% endif %}
<br><br>
<!-- 2019 -->
<h2>완료 목록({{request.user}})</h2>


1231231232

<table class="table table-bordered">
    <tr>
        <td>todo(my)</td>
        <td>todo(전체)</td>
        <td>question</td>
    </tr>
    <tr>
        <td>
            <a href="/todo/todolist/uncomplete/me"> 미완료 ({{todo_count_uncomplete}})</a> <br>
            <a href="/todo/todolist/complete/me"> 완료 ({{todo_count_complete}})</a>
        </td>
        <td>
            <a href="/todo/category/_none/"> 전체(미완료)({{total_todo_count_uncomplete}}) </a><br>
            <a href="/todo/completeList/total"> 전체(완료) ({{total_todo_count_complete}}) </a>
        </td>
        <td>
            {% for category in category_list %}
                <a href="{{category.get_absolute_url}}">{{ category.name }} ({{ category.todo_set.count }})</a>
            {% endfor %}
        </td>
    </tr>
</table>

<div class="input-group">
    <input type="text" id="search-input" onkeyup="wait_for_enterkey_todo()" class="form-control"
           placeholder="Search for..."/>
    <span class="input-group-btn">
        <button class="btn btn-secondary" type="button" onclick="search_todo();">Go!</button>
    </span>
</div>
<br>
    {% if category %}
        카테고리 :
        <small class="text-muted">: {{ category }}</small>
        <br><br>
    {% endif %}

<a href = "{% url "todo:todo_new" %}" class="btn btn-outline-info float-right btn-sm">입력</a>
<a href="" class="btn btn-outline-info float-right btn-sm" id="todo_delete_button"> 삭제 </a>


<br><br>

<table class="table table-bordered" id="todo_list">
    <tr>
        <td>check</td>
        <td>분류</td>
        <td>title</td>
        <td>소요 시간</td>
        <td>완료 일자</td>
        <td>완료 여부</td>
    </tr>

    {% if object_list.exists %}
        {% for p in object_list %}
        <tr>
            <td>
                <input type="checkbox" id="{{p.pk}}" class="td_check">
            </td>
            <td>{{p.classification}}</td>
            <td>
                <a href="" id={{p.id}} class="title_for_list">{{p.title}}</a><br>
                {% if request.user == p.author %}
                    <a class="badge badge-pill badge-dark" href="{% url "todo:todo_edit" p.id %}">수정</a>
                    <a class="badge badge-pill badge-dark" href="{% url "todo:todo_delete" p.pk %}">삭제</a>
                {% endif %}
            </td>
            <td>{{p.elapsed_time}}</td>
            <td>{{p.updated}}</td>
            <td>{{p.completion}}</td>
        </tr>
        {% endfor %}
    {% else %}
        <tr>
            <td colspan="6">
                <h4>아직 게시물이 없습니다.</h4>
            </td>
        </tr>
    {% endif %}
</table>
{% if is_paginated %}
  {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">이전</a>
  {% endif %}
  {{ page_obj.number }} 페이지
  {% if page_obj.has_next %}
    <a href="?page={{page_obj.next_page_number}}">다음</a>
  {% endif %}
{% endif %}
<hr>

<!-- modal area -->
<button type="button" id="myModal_button" class="btn btn-primary invisible" data-toggle="modal" data-target="#myModal">
    Open modal
</button>

<button type="button" id="myModal_button2" class="btn btn-primary invisible" data-toggle="modal"
        data-target="#myModal2">
    Open modal
</button>

<!-- The Modal -->
<div class="modal fade" id="myModal">
    12
</div>

<!-- The Modal -->
<div class="modal fade modal-xl" id="myModal2">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Modal Heading</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <!-- Modal body -->
            <div class="modal-body">
                <!-- Comments Form -->
                    <h5 class="card-header">Leave a Comment:
                    </h5>
                    <div class="card-body">

                        <form method="post" action="{{object.get_absolute_url}}new_comment/">{% csrf_token %}
                            <div class="form-group">
                                {{ comment_form | crispy }}
                            </div>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
            </div>
            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>


{% endblock %}

<script type="text/javascript">

{% block extra_js %}

function search_todo(){
    var search_value = document.getElementById('search-input').value;
    location.href="/todo/search/" + search_value + "/";
}

function wait_for_enterkey_todo(){
    if (window.event.keyCode == 13){
        search_todo();
    }
}

$(document).ready(function(){
    var id;
    $("#todo_list a[class='title_for_list']").click(function(e){

        // alert("삭제 버튼 클릭 2")

        e.preventDefault();
        window.history.pushState("", "", '/todo/')
        id = $(this).attr('id');

        // window.location.href = "www.daum.net";

        $.get(id)
            .done((html) => {
                console.log(html);
                $('#myModal_button').hide();
                $("#myModal").html(html)
                $( "#myModal_button" ).trigger( "click" );
                window.history.pushState("", "", '/todo/todolist/complete/me/')

            })
            .fail(() => {
                console.log("fail");
            })
            .always(() => {
                console.log('always');
            })
    });
})


$(document).ready(function(){

    $('.comment_button_for_todo_detail').click(function(e){
        e.preventDefault();
        id=$(this).attr('id');
        alert('id : ', id)
    })

    $('#todo_delete_button').click(function(e){
        e.preventDefault();
        // todo_check
        alert("삭제 버튼 ")
        // Get checked checkboxes
        var todo_arr = [];
        $('.td_check').each(function() {
            if (jQuery(this).is(":checked")) {
                var id = this.id;
                todo_arr.push(id);
            }
        });
        alert('todo_arr : '+ todo_arr)

        $.ajax({
          type: "POST",
          url: 'todo_delete_ajax/',
          data: {
              'todo_arr[]':todo_arr,
              csrfmiddlewaretoken: '{{ csrf_token }}'
          },
            success: function(result) {
                alert('todo_delete_ajax is success ');
                jQuery('input:checkbox:checked').parents("tr").remove();
            }
        });
    })


})

{% endblock %}


</script>

todo/templates/todo/todo_list_complete_card.html
{% extends "todo/layout.html" %}
{%block title %}todo 완료(me){% endblock %}

{%block extra_css %}

.modal-dialog {
  width: 100%;
  height: 50%;
  margin: 0;
  padding: 0;
}

.modal-content {
    width:132%;
}

{% endblock %}

{%block content5 %}

<br>
<h2> Todo 완료 목록 </h2>

{% if object_list.exists%}
    {% for p in object_list %}
        <table class="table table-bordered">
            <tr>
                <td style="width: 20%">작성자</td>
                <td>{{p.author}}</td>
            </tr>
            <tr>
                <td style="width: 20%">task</td>
                <td>{{p.title}}</td>
            </tr>
            <tr>
                <td style="width: 20%">상세 사항</td>
                <td>
                    {{ p.get_markdown_content | safe }}
                </td>
            </tr>
            <tr>
                <td style="width: 20%">note</td>
                <td>
                    <a href="https://{{p.note}}">note</a>
                </td>
            </tr>
            <tr>
                <td>시작 시간</td>
                <td>{{p.created}}</td>
            </tr>
            <tr>
                <td>소요 시간</td>
                <td>{{p.elapsed_time}}</td>
            </tr>
                    <tr>
                        <td colspan="2">
                        {% if request.user == p.author %}
                        <button type="button" class="btn btn btn-outline-danger btn-sm float-right" onclick="updateTodo(this.id)">
            				<a
            				href="{% url "todo:todo_complete" p.id %}"
                            class=""
                            data-target-id=""
                            data-message=""
                            >
                                완료
                            </a>
                        </button>

                        <button type="button" class="btn btn btn-outline-danger btn-sm float-right" onclick="updateTodo(this.id)">
            				<a
            				href="{% url "todo:todo_delete" p.pk %}"
                            class=""
                            data-target-id=""
                            data-message=""
                            >
                                삭제
                            </a>
                        </button>

                        <button type="button" class="btn btn btn-outline-danger btn-sm float-right" onclick="updateTodo(this.id)">
            				<a
            				href="{% url "todo:todo_edit" p.id %}"
                            class=""
                            data-target-id=""
                            data-message=""
                            >
                                수정
                            </a>
                        </button>
                        {% endif %}
                    </td>
                </tr>
        </table>
    {% endfor %}
{% else %}
    <h4>아직 게시물이 없습니다.</h4>
{% endif %}

<script type="text/javascript">
    // modal 이벤트 : 상세 보기
    $(document).on('click', '.recommand_button', function (e) {
        e.preventDefault();
        var href = $(this).attr("href");
		alert(href);
</script>

{% endblock %}